//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asfalter.Engine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit_record
    {
        public int idUnitRecord { get; set; }
        public int unitId { get; set; }
        public System.DateTime currentTime { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> speed { get; set; }
    
        public virtual unit unit { get; set; }
    }
}
